name: publish

on: 
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'tag name'
        required: true
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          ./make_linux.sh
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./build/*
          name: build
     
  osx:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          ./make_osx.sh
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./build/*
          name: build
